# Generated by Django 3.2.3 on 2021-05-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=100, unique=True)),
                ('pool_access', models.CharField(max_length=100)),
                ('pool_status', models.BooleanField()),
                ('swap_amount', models.CharField(max_length=100)),
                ('pool_adress', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eth_adddress', models.CharField(max_length=100, unique=True)),
                ('pool_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
