# Generated by Django 2.2.2 on 2021-05-20 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210520_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='pool_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Pool'),
        ),
    ]
