# Generated by Django 3.2.3 on 2021-05-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210521_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelist',
            name='eth_adddress',
            field=models.CharField(max_length=100),
        ),
    ]
