# Generated by Django 3.2.3 on 2021-05-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_whitelist_eth_adddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_tier',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Bonus Tier', 'Bonus Tier')], default='Tier 1', max_length=100),
        ),
    ]
