# Generated by Django 3.2.3 on 2021-05-22 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pool_pool_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
