# Generated by Django 3.2.3 on 2021-05-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210523_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelist',
            old_name='eth_adddress',
            new_name='eth_address',
        ),
    ]
