# Generated by Django 3.2.3 on 2021-05-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_rename_eth_adddress_whitelist_eth_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='pool_adress',
            new_name='pool_address',
        ),
    ]
