# Generated by Django 3.2.3 on 2021-05-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_pool_adress_pool_pool_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_raised_amount',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
