# Generated by Django 3.2.3 on 2021-05-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_pool_pool_raised_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_coin_decimal',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_coin_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_coin_symbol',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_coin_total_supply',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
