# Generated by Django 3.2.3 on 2021-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20210523_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='pool_coin_image',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_tier',
            field=models.CharField(choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3'), ('Tier 4', 'Tier 4')], default='Tier 1', max_length=100),
        ),
    ]
